# 当异常发生时，ruby将exception对象的引用放在全局变量$!中